import type { Copy } from '../getCopy';

/** English copy – Damascus event */
export const copyDamascusEn: Copy = {
  cityToggle: {
    damascus: 'Damascus',
    aleppo: 'Aleppo',
  },
  header: {
    brand: 'EDUGATE',
    brandHighlight: 'EXPO',
    whyEduGate: 'Why EDUGATE EXPO',
    exhibitors: 'Exhibitors',
    visitInfo: 'Visit Info',
    faq: 'FAQ',
    contactUs: 'Contact Us',
    registerNow: 'Register Now',
  },
  hero: {
    badge: 'EDUGATE EXPO 2026 • August 9–11',
    openingDate: 'August 9–11',
    title: 'Your Future',
    titleHighlight: 'Starts Here',
    subtitle:
      "Your decision today shapes your children's tomorrow. Join Damascus's first-ever comprehensive Schools and Institutes Exhibition.",
    visitExpo: 'Visit the Expo',
    exhibitorReg: 'Exhibitor Registration',
    openingDay: 'Opening Day',
    exhibitors: 'Exhibitors',
    exhibitorsCount: '50+',
    freeEntry: 'Free',
    entryFee: 'Entry Fee',
  },
  aboutExpo: {
    title: 'About the Expo',
    description:
      "Damascus hosts the first-ever Schools and Institutes Exhibition. A comprehensive platform bringing together leading private schools, language centers, and e-learning platforms—all under one roof.",
  },
  whyParents: {
    label: 'Why Parents Visit',
    title: 'Making Informed Decisions',
    titleHighlight: "For Your Children's Future",
    saveTime: {
      title: 'Save time and effort',
      desc: 'Avoid dozens of individual school visits and find everything you need in one place.',
    },
    accurateInfo: {
      title: 'Accurate information',
      desc: 'Get information directly from the source—school administrations and educators.',
    },
    compareSchools: {
      title: 'Compare schools',
      desc: 'Compare schools with ease in one location (National – International – Languages).',
    },
    exclusiveOffers: {
      title: 'Exclusive offers',
      desc: 'Benefit from exclusive registration discounts and specialized consultations.',
    },
  },
  whyExpo: {
    title: 'Why',
    titleHighlight: 'EDUGATE EXPO?',
    subtitle: 'Connecting academic institutions with parents to evolve the educational process.',
    introduceParents: { title: 'Introduce parents', desc: 'To private schools and their diverse educational programs.' },
    assistFamilies: { title: 'Assist families', desc: 'In choosing the most suitable school for their children.' },
    fosterCompetition: { title: 'Foster competition', desc: 'Positive competition between schools to raise the quality of education.' },
    showcaseLatest: { title: 'Showcase latest', desc: 'Educational methods and technologies.' },
    networkingHub: { title: 'Networking hub', desc: 'Create a networking hub for schools and educational institutions.' },
  },
  forExhibitors: {
    title: 'For',
    titleHighlight: 'Exhibitors',
    subtitle: 'Why showcase at EDUGATE EXPO? Build direct trust with parents and highlight your excellence.',
    strengthenPresence: { title: 'Strengthen presence', desc: "Strengthen your school's presence in the educational market." },
    reachThousands: { title: 'Reach thousands', desc: 'Reach thousands of families actively looking to enroll.' },
    increaseEnrollment: { title: 'Increase enrollment', desc: 'Increase student enrollment numbers.' },
    showExcellence: { title: 'Show excellence', desc: 'Display your strengths and distinctive features.' },
    buildTrust: { title: 'Build trust', desc: 'Build direct trust with parents.' },
  },
  whyParentsVisit: {
    label: 'Why should parents visit the expo?',
    saveTime: 'Save time and effort instead of visiting dozens of schools',
    accurateInfo: 'Get accurate information directly from the source',
    compareEasily: 'Compare schools easily',
    exclusiveOffers: 'Benefit from offers and discounts',
    informedDecision: "Make an informed decision for your children's future",
  },
  duringVisit: {
    title: 'During your',
    titleHighlight: 'Visit',
    subtitle:
      'Visiting hours are from 4:00 PM to 10:00 PM. Free shuttle buses are available in front of Sana and in Bab Tuma square from 4:00 PM till 9:00 PM.',
    activities: [
      {
        time: '04:00 PM',
        title: 'Discover private schools',
        location: 'Main Exhibition Hall',
        desc: 'Discover prominent private schools and their curricula (National – International – Languages).',
      },
      {
        time: '05:15 PM',
        title: 'Compare programs',
        location: 'Information Center',
        desc: 'Compare various programs and review tuition fees and available payment plans.',
      },
      {
        time: '06:30 PM',
        title: 'Meet administrators',
        location: 'Meeting Pods',
        desc: 'Meet directly with school administrations and educators to get your questions answered.',
      },
      {
        time: '07:45 PM',
        title: 'Educational consultations',
        location: 'Consultation Wing',
        desc: "Receive specialized educational consultations specifically for your child's needs.",
      },
      {
        time: '09:00 PM',
        title: 'Exclusive discounts',
        location: 'Registration Desk',
        desc: 'Avail exclusive registration discounts only available during the expo.',
      },
      {
        time: '10:00 PM',
        title: 'Doors Close',
        location: 'All Zones',
        desc: 'The expo is open daily from 4:00 PM to 10:00 PM.',
      },
    ],
  },
  campusSpotlight: {
    badge: 'Educational Excellence',
    title: 'Integrated Interactive',
    titleHighlight: 'Experience',
    description:
      "Explore educational, recreational, and technical options. Compare programs and services directly before making the best decision for your children's future.",
    languageCenters: { title: 'Language Centers', desc: 'Leading institutes for linguistic mastery.' },
    eLearning: { title: 'E-Learning', desc: 'Digital platforms and educational software.' },
    specialNeeds: { title: 'Special Needs', desc: 'Dedicated training and support centers.' },
    virtualSchools: { title: 'Virtual Schools', desc: 'The future of flexible academic learning.' },
  },
  schools: {
    layout: 'cards',
    title: 'Participating Institutions',
    subtitle: 'Explore some of the leading schools and institutes joining EDUGATE EXPO 2026.',
    viewAll: 'View All Participating Schools',
    scholarships: 'Scholarships Available',
    details: 'Details',
    items: [
      {
        name: 'Damascus International',
        location: 'Mazzeh, Damascus',
        type: 'International',
        image: 'https://images.unsplash.com/photo-1492538368677-f6e0afe31dcc?w=800&q=80',
        rating: 4.9,
      },
      {
        name: 'Al-Amal Private School',
        location: 'Malki, Damascus',
        type: 'National',
        image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
        rating: 4.9,
      },
      {
        name: 'Syrian Modern Academy',
        location: 'Kafarsouseh, Damascus',
        type: 'National & Languages',
        image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
        rating: 4.9,
      },
    ],
  },
  sponsors: {
    label: 'Sponsors & Media Partners',
    title: 'Sponsors & Media Partners',
    subtitle: '',
    groups: [],
  },
  sectors: {
    label: 'Exhibitors',
    title: 'Exhibitors',
    subtitle: '',
    items: [],
  },
  gallery: {
    title: 'Moments of',
    titleHighlight: 'Inspiration',
    subtitle: 'Glimpses from past fairs where futures were decided and dreams took flight.',
  },
  testimonials: {
    title: 'Success',
    titleHighlight: 'Stories',
    subtitle: 'Hear from the community about their experiences and the impact the fair had on their educational journey.',
    t1: {
      quote:
        'Comparing different schools in one place saved me weeks of visits. I found the perfect curriculum for my daughter.',
      author: 'Nour Al-Homsi',
      role: 'Parent',
    },
    t2: {
      quote:
        'The direct meetings with school owners helped us understand their vision for education and student development.',
      author: 'Ahmad Mansour',
      role: 'Education Consultant',
    },
    t3: {
      quote:
        'Finally, an event that brings all educational options under one roof in Damascus. A must-visit for every family.',
      author: 'Lina Kabbani',
      role: 'Parent',
    },
  },
  faq: {
    title: 'Frequently Asked',
    titleHighlight: 'Questions',
    subtitle: 'Everything you need to know about EDUGATE EXPO 2026.',
    items: [
      {
        q: 'Is the expo for students only?',
        a: 'The expo is open to students, parents, and anyone interested in education and professional development.',
      },
      { q: 'Is there an entry fee?', a: 'Entry is free of charge.' },
      {
        q: 'Can students register during the expo?',
        a: 'Yes, direct communication and registration will be available with many participating institutions.',
      },
      { q: 'What are the visiting hours?', a: 'Visiting hours are from 4:00 PM to 10:00 PM.' },
      {
        q: 'Is there transportation to the Fairground (Fair City)?',
        a: 'Yes, free shuttle buses are available in front of Sana and in Bab Tuma square from 4:00 PM till 9:00 PM.',
      },
    ],
  },
  registration: {
    title: 'Exhibitor Registration',
    subtitle:
      "Strengthen your school's presence and reach thousands of families. Join us as an exhibitor, sponsor, or media partner.",
    registerVisitor: 'Register Now',
    registerExhibitor: 'Register as Exhibitor',
    goldenExhibitor: 'Golden Exhibitor',
    silverExhibitor: 'Silver Exhibitor',
    standard: 'Standard',
    sponsorsPartners: 'Sponsors & Media Partners',
    showExhibitorTiers: true,
    visitorPrimary: false,
  },
  contact: {
    badge: 'Get In Touch',
    title: 'Contact Us',
    description: 'We are here to answer your questions and provide all the information you need.',
    phone: {
      title: 'Phone',
      number: '+963 11 334 4805',
      copied: 'Copied!',
    },
    email: {
      title: 'Email',
      address: 'info@edugate-expo.com',
    },
    facebook: {
      title: 'Facebook',
      text: 'EDUGATE EXPO',
    },
    instagram: {
      title: 'Instagram',
      text: '@EdugateExpo',
    },
    whatsapp: {
      title: 'WhatsApp',
      text: '+963 992 874 838',
    },
    success: {
      title: 'Message Sent Successfully',
      message: 'Thank you for reaching out. We will get back to you shortly.',
      sendAnother: 'Send another message',
    },
    form: {
      title: 'Send a Message',
      name: 'Name',
      namePlaceholder: 'Your full name',
      email: 'Email',
      emailPlaceholder: 'Your email address',
      subject: 'Subject',
      subjectPlaceholder: 'Message subject',
      message: 'Message',
      messagePlaceholder: 'How can we help you?',
      sending: 'Sending...',
      submit: 'Send Message',
    },
  },
  footer: {
    brand: 'EDUGATE EXPO 2026',
    tagline: "Damascus's first comprehensive Schools and Institutes Exhibition. Your future starts here.",
    openingDates: {
      days: 'August 9-10-11,',
      month: '',
      year: '2026',
    },
    eventTime: '4:00 PM to 10:00 PM',
    quickLinks: 'Quick Links',
    aboutExpo: 'About the Expo',
    forParents: 'For Parents',
    forExhibitors: 'For Exhibitors',
    faq: 'FAQ',
    venueTitle: 'Venue',
    dateTitle: 'Event Date',
    contact: 'Contact',
    phone: '+963 992 874 838',
    address: 'Damascus, Syria',
    email: 'info@edugate-expo.com',
    organizer: 'Organized by',
    organizerName: 'Vulcan',
    copyright: '© 2026 Vulcan. All rights reserved.',
    facebook: 'Facebook',
    instagram: 'Instagram',
  },
  media: {
    heroImage: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=2070&auto=format&fit=crop',
    heroVideo: '',
    heroPoster: '',
    aboutBanner: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070',
    campus1: '/images/campusspotlight-1.jpg',
    campus2: '/images/campusspotlight-2.jpg',
    whyParents: [
      'https://images.unsplash.com/photo-1753715613651-749ef230482c?q=80&w=2070',
      '/images/accurate-information.jpg',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070',
      'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?q=80&w=2070',
    ],
  },
};
